packages:
  - apps/*
  - tools/*

catalog:
  "@types/node": ^22.15.0
  eslint: ^9.26.0
  prettier: ^3.5.3
  typescript: ^5.8.3

catalogs:
  react19:
    "@types/react": ^19.1.3
    "@types/react-dom": ^19.1.3
    react: ^19.1.0
    react-dom: ^19.1.0
