[package]
name = "inkk"
version = "0.1.0"
edition = "2021"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "inkk_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dev]
incremental = true  # Compile binary in smaller steps.

[profile.release]
codegen-units = 1   # Allows LLVM to perform better optimization.
lto = true          # Enables link-time-optimizations.
opt-level = "z"     # Determines the focus of the compiler. Use 3 to optimize performance, z to optimize for size, and s for something in-between.
panic = "abort"     # Higher performance by disabling panic handlers.
strip = true        # Ensures debug symbols are removed.
